[versions]
# SDK Versions
targetSdk = "36"
compileSdk = "36"
minSdk = "23"
ndkVersion = "28.2.13676358"

# App Version
versionCode = "29"
versionName = "1.2.7-dev"

# Plugin Versions
agp = "8.13.2"
androidTools = "32.0.0"
kotlin = "2.2.21"
ksp = "2.3.4"
hilt = "2.59"

# Google Services
gms = "4.4.4"
crashlytics = "3.0.6"
firebaseBom = "34.8.0"
firebasePerfPlugin = "2.0.2"
playIntegrity = "1.6.0"

# Development Tools
leakcanary = "2.14"
detekt = "1.23.8"
dependencyGuard = "0.5.0"

# AndroidX Libraries
activityKtx = "1.12.2"
appcompat = "1.7.1"
cardview = "1.0.0"
coreKtx = "1.17.0"
constraintlayout = "2.2.1"
coreSplashscreen = "1.2.0"
fragmentKtx = "1.8.9"
navigation = "2.9.6"
recyclerview = "1.4.0"
swiperefreshlayout = "1.2.0"
viewpager2 = "1.1.0"

# Kotlin Coroutines
kotlinxCoroutines = "1.10.2"

# Lifecycle Libraries
lifecycle = "2.10.0"

# Datastore
datastore = "1.2.0"

# Room Libraries
room = "2.8.4"

# Paging3
paging = "3.3.6"

# UI components
material = "1.14.0-alpha08"

# Networking
retrofit = "3.0.0"
moshi = "1.15.2"
okhttp = "5.3.2"

# Java Compatibility
desugarJdkLibs = "2.1.5"

# Testing Libraries
androidxJunit = "1.3.0"
espresso = "3.7.0"
coreTesting = "2.2.0"
jacoco = "0.8.14"
junitVersion = "4.13.2"
junitVintage = "6.0.1"
json = "20251224"
kotest = "6.1.0"
kotlinxKover = "0.9.4"
mockk = "1.14.6"
mockitoKotlin = "6.1.0"
mockito = "5.20.0"
robolectric = "4.16.1"
androidxTest = "1.7.0"
truth = "1.4.5"
turbine = "1.2.1"

# Image Loading
glide = "5.0.5"

# Third-party Libraries
expandableTextView = "1.0.7"
cpa = "0.1.4"
shimmer = "0.5.0"
moduleGraph = "2.9.0"

[libraries]
# AndroidX Libraries
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityKtx" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "coreKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

# Lifecycle
androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "lifecycle" }
androidx-lifecycle-livedata-core = { group = "androidx.lifecycle", name = "lifecycle-livedata-core", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }

# Navigation
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }

# Paging
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }

# Datastore
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Room Libraries
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# UI components
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Networking
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Development tools
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

# Testing Libraries
# AndroidX Testing Libraries
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
androidx-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragmentKtx" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTest" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTest" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxJunit" }

# Junit Testing Libraries
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junitVintage" }

# Json Libraries
json = { module = "org.json:json", version.ref = "json" }

# Kotest Libraries
kotest-kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

# Kotlin Testing Libraries
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

# Mockito Libraries
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
mockito-android-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

# Mockk Libraries
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" } # use for instrumentation tests
mockk = { module = "io.mockk:mockk", version.ref = "mockk" } # use for unit tests

# Other Testing Libraries
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# Image Loading
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

# Google Services
play-integrity = { group = "com.google.android.play", name = "integrity", version.ref = "playIntegrity" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }

# Third-party Libraries
country-picker-android = { group = "com.github.waffiqaziz", name = "country-picker-android", version.ref = "cpa" }
expandable-textview = { group = "io.github.glailton", name = "expandabletextview", version.ref = "expandableTextView" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

# Hilt-dagger
hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }

kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Dependencies of the included build-logic
android-gradleApiPlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "crashlytics" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kover-gradlePlugin = { group = "org.jetbrains.kotlinx.kover", name = "org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kotlinxKover" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }


[plugins]
# Core
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# Google
gms-googleServices = { id = "com.google.gms.google-services", version.ref = "gms" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }

# Others
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
module-graph = { id = "com.jraska.module.graph.assertion", version.ref = "moduleGraph" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinxKover" }

# Custom Plugins
bazzmovies-android-application = { id = "bazzmovies.android.application" }
bazzmovies-android-application-firebase = { id = "bazzmovies.android.application.firebase" }
bazzmovies-android-application-jacoco = { id = "bazzmovies.android.application.jacoco" }
bazzmovies-android-library-jacoco = { id = "bazzmovies.android.library.jacoco" }
bazzmovies-android-library-kover = { id = "bazzmovies.android.library.kover" }
bazzmovies-android-library = { id = "bazzmovies.android.library" }
bazzmovies-android-feature = { id = "bazzmovies.android.feature" }
bazzmovies-android-room = { id = "bazzmovies.android.room" }
bazzmovies-detekt = { id = "bazzmovies.detekt" }
bazzmovies-glide = { id = "bazzmovies.glide" }
bazzmovies-hilt = { id = "bazzmovies.hilt" }
bazzmovies-hilt-test = { id = "bazzmovies.hilt.test" }
bazzmovies-jvm-library = { id = "bazzmovies.jvm.library" }
bazzmovies-shared-test = { id = "bazzmovies.shared.test" }

[bundles]
datastore = [
  "androidx-datastore-core",
  "androidx-datastore-preferences"
]

firebase = [
  "firebase-analytics",
  "firebase-crashlytics",
  "firebase-performance"
]

kotest = [
  "kotest-kotest-assertions-core",
  "kotest-property",
  "kotest-runner-junit5"
]

retrofit = [
  "retrofit",
  "retrofit-converter-moshi",
  "moshi-kotlin",
  "okhttp-logging-interceptor"
]
